version: "3.7"

services:
  db:
    image: postgres
    restart: always
    container_name: bed_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d/"
      # - "./bed_model:/var/lib/postgresql/data"
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=joe@forensx.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PDADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    depends_on:
      - "db"
    logging:
      driver: none
    networks:
      - db_network
    tty: true
  
  client:
    image: rapidsai/rapidsai:cuda11.0-runtime-ubuntu18.04
    container_name: bed_client 
    runtime: nvidia
    volumes:
        - "./bed_model:/rapids/notebooks/bed_model"
    stdin_open: true
    ports:
      - "8888:8888"
      - "8787:8787"
      - "8786:8786"
    networks:
      - db_network

networks: 
  db_network:
    driver: bridge